language: node_js

node_js:
  - 'stable'
  - '4'

sudo: false

matrix:
  fast_finish: true

branches:
  only:
  - master

cache:
  directories:
    - node_modules

git:
  depth: 1

before_script:
  #set up the virtual screen for Firefox
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  - npm i -g typescript typings
  - typings install
  - tsc

install:
  - npm install