language: node_js
node_js:
- stable
sudo: false
matrix:
  fast_finish: true
cache:
  directories:
  - node_modules
branches:
  except:
  - gh-pages
git:
  depth: 1
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- npm i -g typescript
install:
- npm install
addons:
  firefox: latest
after_success:
- openssl aes-256-cbc -K $encrypted_5e96d350c582_key -iv $encrypted_5e96d350c582_iv
  -in docs_rsa.enc -out build/docs/docs_rsa -d
- chmod 0600 build/docs/docs_rsa
- eval "$(ssh-agent -s)"
- ssh-add build/docs/docs_rsa
- npm i -g @compodoc/compodoc
- bash ./build/docs/publish-docs.sh
before_deploy:
- tsc ./build/prepare-npm-publish.ts
- node ./build/prepare-npm-publish.js
- tsc index.ts --declaration --target es5 --module commonjs
deploy:
  skip_cleanup: true
  provider: npm
  email: dvabuzyarov@gmail.com
  api_key:
    secure: eCg8bNY3nWuLauyC41Dyun4ETAFQHniI9qcvJ5iH+3zfECsqflhZRDbMFlDAIkqIvM8jGcu3K3nv8wtJcdXuzjT3aONsHEu7mWvqixyoj3Izbu4raFx8qJYJvN5sz40YOGK3HWzcHeQTcMQWBTTDoUNRETJSbgHS9hOaivEByZSe+sOrnWzdmxggc5Ur5BT+hQZbnC9EBdMgavAO/YYA1fGyj/EBrUNbKv7ULCrbN9D7NWUaLjIEhGEpu10JCqfWzWPD7Fff6qln3FPEkinUvjAC30DmyNiMEd4HqVFVufzUca02bEcZxVdCV33QuvvNqBU/Ry7tj71hsJAhXwjrgGaPeyzKYqlnSM/R2DVLl2YTarIGU7cUuYiwyx+I4tEYsG6EesH9UX/Uhx3D+v2t/tiIso5FTON+S1wOcAX74rIfl6fBw+8S4HFFUkrDIIMVbdZQ+Fw2AP1j/HLFkcMegtujavZ9iq70MeMaytRB1oK5xk8MEySTA6JMdn6e5rnhbCRsZv3Rk9Z7TDvHwivVvxwyLMgfacjHg0zdVoYOxd0A3/22vwgOL/AGcFGFSZxd0ogJJcTE3gzBSzt0SwA4ToNoGaYHYHnJOY9Mt0MwQahF0DGAv/mgBUZboyyBO0rDeV9mGYN/JwTCJ6s7DHWx/CuvNotY/8rgsTomGdqzsQM=
  on:
    tags: true
    all_branches: true
    repo: dvabuzyarov/moq.ts
